function classChange(){
	var selectBox = document.getElementById("classes");
	var selected = selectBox.options[selectBox.selectedIndex].value;

  if(selected=="barbarian"){
    $('.class').hide();
    $('#barbarianImage').show();
    $('#barbarianText').show();
    $('#barbarianFullText').show();
  }
  if(selected=="bard"){
    $('.class').hide();
    $('#bardImage').show();
    $('#bardText').show();
    $('#bardFullText').show();
  }
  if(selected=="cleric"){
    $('.class').hide();
    $('#clericImage').show();
    $('#clericText').show();
    $('#clericFullText').show();
  }
  if(selected=="druid"){
    $('.class').hide();
    $('#druidImage').show();
    $('#druidText').show();
    $('#druidFullText').show();
  }
  if(selected=="fighter"){
    $('.class').hide();
    $('#fighterImage').show();
    $('#fighterText').show();
    $('#fighterFullText').show();
  }
  if(selected=="monk"){
    $('.class').hide();
    $('#monkImage').show();
    $('#monkText').show();
    $('#monkFullText').show();
  }
  if(selected=="paladin"){
    $('.class').hide();
    $('#paladinImage').show();
    $('#paladinText').show();
    $('#paladinFullText').show();
  }
  if(selected=="ranger"){
    $('.class').hide();
    $('#rangerImage').show();
    $('#rangerText').show();
    $('#rangerFullText').show();
  }
  if(selected=="rogue"){
    $('.class').hide();
    $('#rogueImage').show();
    $('#rogueText').show();
    $('#rogueFullText').show();
  }
  if(selected=="sorcerer"){
    $('.class').hide();
    $('#sorcererImage').show();
    $('#sorcererText').show();
    $('#sorcererFullText').show();
  }
  if(selected=="warlock"){
    $('.class').hide();
    $('#warlockImage').show();
    $('#warlockText').show();
    $('#warlockFullText').show();
  }
  if(selected=="wizard"){
    $('.class').hide();
    $('#wizardImage').show();
    $('#wizardText').show();
    $('#wizardFullText').show();
  }
}
